name: Run Attendance

on:
  workflow_dispatch:   # 수동 실행 가능
  push:
    paths:
      - "**/*.py"
      - "requirements.txt"

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Restore service account key from secret
        run: echo "$GCP_SERVICE_ACCOUNT_KEY" > service_account.json
        env:
          GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Run attendance script
        run: python 출석.py
